module.exports = function(grunt) {
  grunt.initConfig({
    sass: {
      dev: {
        files: {
          "public/css/dist/app.css": "web/css/core/app.scss"
        },
        options: {
          style: "expanded",
          sourcemap: "none",
          lineNumbers: true
        }
      }
    },
    autoprefixer: {
      dist: {
        files: {
          "web/css/dist/app.css":  "web/css/dist/app.css"
        },
        options: {
          browsers: ['last 4 versions', 'ie 8', 'ie 9']
        }
      }
    },
    coffee: {
      compile: {
        options: {
          bare: true,
          join: true,
          //sourceMapDir:  "/assets"
        },
        files: {
          'web/js/tmp/core.js': ['web/js/core/*.coffee']
        }
      }
    },
    concat: {
      options: {
        separator: ";"
      },
      dist: {
        src: [ "web/js/vendor/*.js", "web/js/tmp/core.js",  "web/js/core/app.js"],
        dest:  "web/js/dist/app.js"
      }
    },
    uglify: {
      dev: {
        options: {
          beautify: true,
          mangle: false
        },
        src:  "web/js/dist/app.js",
        dest:  "web/js/dist/app.js"
      }
    },
    watch: {
      sass: {
        files: [ "web/css/**/*.scss", "web/css/**/*.css"],
        tasks: ["sass"],
      },
      coffee: {
        files:  "web/js/**/*.coffee",
        tasks: ["coffee"]
      },
      concat: {
        files:  ["web/js/**/*.coffee", "web/js/**/*.js"],
        tasks: ["concat"]
      },
      options: {
        livereload: true
      }
    }
  });
  grunt.loadNpmTasks("grunt-contrib-sass");
  grunt.loadNpmTasks("grunt-autoprefixer");
  grunt.loadNpmTasks("grunt-contrib-coffee");
  grunt.loadNpmTasks("grunt-contrib-concat");
  grunt.loadNpmTasks("grunt-contrib-uglify");
  grunt.loadNpmTasks("grunt-contrib-watch");

  return grunt.registerTask("default", ["sass","autoprefixer", "coffee", "concat", "watch"]);
};

// ---
// generated by coffee-script 1.9.2
